[0m13:02:45.417074 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101dc54c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103cf8a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051467f0>]}


============================== 13:02:45.420742 | 01bb80a3-15f9-403a-9a76-090d1c108f5a ==============================
[0m13:02:45.420742 [info ] [MainThread]: Running with dbt=1.7.2
[0m13:02:45.421116 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/joshuabotticher/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:02:45.421485 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuabotticher/dec-capstone/earthquake_elt/App/dbt_earthquake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:02:45.422860 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.057745874, "process_user_time": 1.185216, "process_kernel_time": 0.102452, "process_mem_max_rss": "98189312", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:02:45.423237 [debug] [MainThread]: Command `dbt run` failed at 13:02:45.423148 after 0.06 seconds
[0m13:02:45.423480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101dc54c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105146af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105114700>]}
[0m13:02:45.423703 [debug] [MainThread]: Flushing usage events
[0m14:59:12.703885 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052a1550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104cde7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d92f40>]}


============================== 14:59:12.706400 | 70ff79c0-1eed-4bbc-ac52-969b32ec6857 ==============================
[0m14:59:12.706400 [info ] [MainThread]: Running with dbt=1.7.2
[0m14:59:12.706753 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/joshuabotticher/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:59:12.707114 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuabotticher/dec-capstone/earthquake_elt/App/dbt_earthquake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:59:12.708482 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.050094333, "process_user_time": 1.165073, "process_kernel_time": 0.105921, "process_mem_max_rss": "99581952", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:59:12.708863 [debug] [MainThread]: Command `dbt run` failed at 14:59:12.708777 after 0.05 seconds
[0m14:59:12.709091 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052a1550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d928b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d928e0>]}
[0m14:59:12.709309 [debug] [MainThread]: Flushing usage events
